### Create Session Route
# @name createSession
POST http://localhost:3000/api/sessions/login
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "test_password"
}

### Get Sessions Route
@cookies = {{createSession.response.headers.Set-Cookie}}

GET http://localhost:3000/api/sessions
Content-Type: application/json
Cookie: {{cookies}}

### Delete Session Route
DELETE http://localhost:3000/api/sessions/logout
Content-Type: application/json
Cookie: {{cookies}}

