### Create Session Route
# @name createSession
POST http://localhost:3000/api/sessions
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "test_password"
}

@accessToken = {{createSession.response.body.accessToken}}

### Get Sessions Route
GET http://localhost:3000/api/sessions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Delete Session Route
DELETE http://localhost:3000/api/sessions
Content-Type: application/json
Authorization: Bearer {{accessToken}}
